
; Session cookies security
session.cookie_httponly = on
session.cookie_samesite = "Strict"

; Do not expose PHP version
expose_php = off

; PHP session persistence config
session.gc_probability = 1
session.gc_divisor = 100
; Same value as CronTask::cronSession
session.gc_maxlifetime = 60480

; Disable dangerous PHP functions to prevent RCE
; This ini conf is used for CLI. Web request are secured by `php_admin_value` in apache config.
; We remove `proc_open` from disabled functions so we can run commands like tools:locales:compile
disable_functions = exec,shell_exec,system,passthru,proc_open,popen,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_unshare,posix_kill,posix_mkfifo,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname,posix_times,posix_getlogin,posix_ttyname,posix_ctermid,posix_getcwd,posix_getgrgid,posix_getgrnam,posix_getgroups,posix_getpgrp,posix_getpid,posix_getppid,posix_getpwnam,posix_getpwuid,posix_getrlimit,posix_getsid,posix_getuid,posix_initgroups,posix_isatty,posix_mknod,posix_access,putenv,dl,openlog,syslog,closelog,apache_child_terminate,apache_setenv
