
# This config file contains all custom Apache settings for GLPI

ServerName localhost

###############################################################
#                          Security                           #
###############################################################
# Harden Apache against fingerprinting
ServerTokens Prod
ServerSignature Off

# Disable dangerous PHP functions to prevent RCE
php_admin_value disable_functions "exec,shell_exec,system,passthru,proc_open,popen,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_unshare,posix_kill,posix_mkfifo,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname,posix_times,posix_getlogin,posix_ttyname,posix_ctermid,posix_getcwd,posix_getgrgid,posix_getgrnam,posix_getgroups,posix_getpgrp,posix_getpid,posix_getppid,posix_getpwnam,posix_getpwuid,posix_getrlimit,posix_getsid,posix_getuid,posix_initgroups,posix_isatty,posix_mknod,posix_access,putenv,dl,openlog,syslog,closelog,apache_child_terminate,apache_setenv"
