name: "CircleCI PHP images"

on:
  push:
    paths:
      - ".github/workflows/circleci-php.yml"
      - "circleci-php/**"
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Build image"
        run: |
          docker build --pull --tag image --build-arg BASE_IMAGE=circleci/php:${{ matrix.php-version }}-fpm-node circleci-php
      - name: "Push image to Docker hub"
        if: github.ref == 'refs/heads/master' && github.repository == 'glpi-project/docker-images'
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          IMAGE_TAG=glpi/circleci-env-core:php_${{ matrix.php-version }}_fpm-node
          docker tag image $IMAGE_TAG
          docker push $IMAGE_TAG
