name: "Github actions Dovecot image"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/githubactions-dovecot.yml"
      - "githubactions-dovecot/**"
  pull_request:
    paths:
      - ".github/workflows/githubactions-dovecot.yml"
      - "githubactions-dovecot/**"
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Build image"
        run: |
          docker build --pull --tag image --build-arg BASE_IMAGE=debian:buster-slim githubactions-dovecot
      - name: "Push image to Docker hub"
        if: github.ref == 'refs/heads/master' && github.repository == 'glpi-project/docker-images'
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          IMAGE_TAG=glpi/githubactions-dovecot:latest
          docker tag image $IMAGE_TAG
          docker push $IMAGE_TAG
      - name: "Push image to Github container registry"
        if: github.ref == 'refs/heads/master' && github.repository == 'glpi-project/docker-images'
        run: |
          echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login -u ${{ secrets.GHCR_USERNAME }} --password-stdin ghcr.io
          IMAGE_TAG=ghcr.io/glpi-project/githubactions-dovecot:latest
          docker tag image $IMAGE_TAG
          docker push $IMAGE_TAG
