name: "GLPI development environment image"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/glpi-development-env.yml"
      - "glpi-development-env/**"
  pull_request:
    paths:
      - ".github/workflows/glpi-development-env.yml"
      - "glpi-development-env/**"
  schedule:
    - cron:  '0 0 * * 1'
  # Enable manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - {base-image: "php:7.4-apache-bullseye", php-version: "7.4", latest: "false"}
          - {base-image: "php:8.0-apache-bullseye", php-version: "8.0", latest: "false"}
          - {base-image: "php:8.1-apache-trixie", php-version: "8.1", latest: "false"}
          - {base-image: "php:8.2-apache-trixie", php-version: "8.2", latest: "false"}
          - {base-image: "php:8.3-apache-trixie", php-version: "8.3", latest: "false"}
          - {base-image: "php:8.4-apache-trixie", php-version: "8.4", latest: "true"}
    steps:
      - name: "Set variables"
        run: |
          OUTPUTS="type=image"
          if [[ "${{ github.ref }}" = 'refs/heads/main' && "${{ github.repository }}" = 'glpi-project/docker-images' ]]; then
              OUTPUTS="$OUTPUTS,push=true"
          fi
          echo "OUTPUTS=$OUTPUTS" >> $GITHUB_ENV
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Login to DockerHub"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
      - name: "Login to Github container registry"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_ACCESS_TOKEN }}"
      - name: "Build and push"
        uses: "docker/build-push-action@v6"
        with:
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
          context: "glpi-development-env"
          outputs: "${{ env.OUTPUTS }}"
          pull: true
          tags: "ghcr.io/glpi-project/glpi-development-env:${{ matrix.php-version }}${{ matrix.latest == 'true' && ',ghcr.io/glpi-project/glpi-development-env:latest' || '' }}"
