name: "Update DockerHub README"

on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"

jobs:
    update-readme:
      runs-on: "ubuntu-latest"
      steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"
      - name: "Update repository description"
        uses: "peter-evans/dockerhub-description@v5"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
          repository: "glpi/glpi"
